### ISSUE TITLE
Support Webpack 5

### ISSUE THREAD

**Issue by zshlomyz** [developit/optimize-plugin#17]
* Webpack@5.22.0
* optimize-plugin@1.0.0
* Node@14.15.4

I added the optimize-plugin to my webpack configuration as described:
```
const OptimizePlugin = require('optimize-plugin');
module.exports = {
 plugins: [
    new HtmlWebpackPlugin(),...]
...
}
```

Then when I run Webpack I got the error:

```
> webpack

(node:24812) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hook.processAssets instead and use
one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
(Use `node --trace-deprecation ...` to show where the warning was created)
[OptimizePlugin] Detected core-js version 3
[OptimizePlugin] Completed in 0ms.
      - ms: Optimize Assets
No polyfills bundle was created.
[OptimizePlugin] Completed in 3712ms.
     937ms: Optimize Assets
     936ms:  └ bundle.js
           719ms: modern
            23ms: modern-minify
            78ms: legacy
     535ms: Bundle Polyfills
           326ms: parse
           157ms: generate
polyfills.legacy.js is 2.41kB and bundles 1 polyfills:
└ Used by bundle.legacy.js:
  └ core-js/modules/es.object.define-property
[webpack-cli] HookWebpackError: Cannot read property 'sections' of null
    at makeWebpackError (C:\Dev\Work\testTs\node_modules\webpack\lib\HookWebpackError.js:49:9)
    at C:\Dev\Work\testTs\node_modules\webpack\lib\Compilation.js:2000:11
    at eval (eval at create (C:\Dev\Work\testTs\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:31:1)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
-- inner error --
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (C:\Dev\Work\testTs\node_modules\source-map\lib\source-map-consumer.js:20:20)
    at SourceMapSource.node (C:\Dev\Work\testTs\node_modules\optimize-plugin\node_modules\webpack-sources\lib\SourceMapSource.js:32:62)
    at SourceMapSource.proto.sourceAndMap (C:\Dev\Work\testTs\node_modules\optimize-plugin\node_modules\webpack-sources\lib\SourceAndMapMixin.js:29:18)
    at C:\Dev\Work\testTs\node_modules\terser-webpack-plugin\dist\index.js:323:27
    at C:\Dev\Work\testTs\node_modules\p-try\index.js:4:10
    at new Promise (<anonymous>)
    at pTry (C:\Dev\Work\testTs\node_modules\p-try\index.js:3:37)
    at run (C:\Dev\Work\testTs\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:24:18)
    at C:\Dev\Work\testTs\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:46:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
caused by plugins in Compilation.hooks.processAssets
TypeError: Cannot read property 'sections' of null
    at new SourceMapConsumer (C:\Dev\Work\testTs\node_modules\source-map\lib\source-map-consumer.js:20:20)
    at SourceMapSource.node (C:\Dev\Work\testTs\node_modules\optimize-plugin\node_modules\webpack-sources\lib\SourceMapSource.js:32:62)
    at SourceMapSource.proto.sourceAndMap (C:\Dev\Work\testTs\node_modules\optimize-plugin\node_modules\webpack-sources\lib\SourceAndMapMixin.js:29:18)
    at C:\Dev\Work\testTs\node_modules\terser-webpack-plugin\dist\index.js:323:27
    at C:\Dev\Work\testTs\node_modules\p-try\index.js:4:10
    at new Promise (<anonymous>)
    at pTry (C:\Dev\Work\testTs\node_modules\p-try\index.js:3:37)
    at run (C:\Dev\Work\testTs\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:24:18)
    at C:\Dev\Work\testTs\node_modules\terser-webpack-plugin\node_modules\p-limit\index.js:46:18
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! test-ts@1.0.0 buildW: `webpack`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the test-ts@1.0.0 buildW script.
```

Can you help, please?
Thanks

**Comment by fernandofleury** [comment]
I think this issue is related to Webpack 5 specifically. I was running into the same problems and decided to downgrade to v4 to try it out (and it worked).

**Comment by developit** [comment]
Yep, it's just not updated for 5 yet. I don't know off-hand what the corresponding plugin hook would be in v5, so if anyone knows and wants to PR it I would be happy to review.
