### ISSUE TITLE
TypeError: OptimizePlugin is not a constructor

### ISSUE THREAD

**Issue by dva** [developit/optimize-plugin#6]
Looks like npm version not yet updated

Latest update: February 18, 2020 – 0.0.1

https://yarnpkg.com/package/optimize-plugin

![image](https://user-images.githubusercontent.com/365010/101815745-abae7580-3b28-11eb-8573-49ac088101bc.png)

> node_modules/webpack-cli/bin/cli.js:93
                                throw err;
                                ^
TypeError: OptimizePlugin is not a constructor
    at Object.<anonymous> (project/internals/webpack/prod.js:41:39)
    at Module._compile (project/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (project/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (project/node_modules/webpack-cli/bin/utils/convert-argv.js:114:13)
    at requireConfig (project/node_modules/webpack-cli/bin/utils/convert-argv.js:116:6)
    at project/node_modules/webpack-cli/bin/utils/convert-argv.js:123:17
    at Array.forEach (<anonymous>)
    at module.exports (project/node_modules/webpack-cli/bin/utils/convert-argv.js:121:15)
    at project/node_modules/webpack-cli/bin/cli.js:71:45
    at Object.parse (project/node_modules/yargs/yargs.js:576:18)
    at project/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (project/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (project/node_modules/webpack/bin/webpack.js:156:2)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
error Command failed with exit code 1.

**Comment by benadam11** [comment]
I also ran into this issue (also using Yarn)

**Comment by developit** [comment]
Heh - sorry about that, with so many repos going live today I forgot to publish this one to npm. It's published now.
